#jdbc url=jdbc://np.ikkikki.com:3306/pbl
jdbc.url=jdbc:log4jdbc:mariadb://np.ikkikki.com:3306/pbl
jdbc.username=sample
jdbc.password=1234
jdbc.driver.classname=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#jdbc.driver.classname=org.mariadb.jdbc.Driver